create table `tasks` (`id` INT NOT NULL AUTO_INCREMENT, 
					  `project_id` INT NOT NULL, 
					  `title` VARCHAR(255), 
					  `created_by` INT NOT NULL, 
					  `created_on` TIMESTAMP NOT NULL, 
					  `description` TEXT,
					  `start_date` DATETIME, 
					  `due_date` DATETIME, 
					  `flag` INT,
					  `percent_complete` INT, 
					  `is_public` BOOL,
                      `current_status` INT,
                      `last_modified` TIMESTAMP NOT NULL,
                      `assigned_to` INT,
					  PRIMARY KEY(`id`), INDEX(`id`))