//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="TaskManagerSoapBinding", Namespace="http://localhost:8080/ProjectServer/services/TaskManager")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(DiscussionMessage))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Account))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(ScheduleItem))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(NamedFieldCollection))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CustomFieldAttribute))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(BinaryAttachment))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(MeetingNoteItem))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(MeetingFollowupItem))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(MeetingAgendaItem))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(NotificationContextObject))]
public class TaskManagerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public TaskManagerService() {
        this.Url = "http://localhost:8080/ProjectServer/services/TaskManager";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("addTaskReturn")]
    public int addTask(Task task) {
        object[] results = this.Invoke("addTask", new object[] {
                    task});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddTask(Task task, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addTask", new object[] {
                    task}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndaddTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    public void dropTask(int taskId) {
        this.Invoke("dropTask", new object[] {
                    taskId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindropTask(int taskId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("dropTask", new object[] {
                    taskId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnddropTask(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    public void modifyTask(Task task) {
        this.Invoke("modifyTask", new object[] {
                    task});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginmodifyTask(Task task, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("modifyTask", new object[] {
                    task}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndmodifyTask(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("getTaskReturn")]
    public Task getTask(int taskId) {
        object[] results = this.Invoke("getTask", new object[] {
                    taskId});
        return ((Task)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTask(int taskId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTask", new object[] {
                    taskId}, callback, asyncState);
    }
    
    /// <remarks/>
    public Task EndgetTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Task)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("getAllTasksReturn")]
    public Task[] getAllTasks() {
        object[] results = this.Invoke("getAllTasks", new object[0]);
        return ((Task[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllTasks(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllTasks", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public Task[] EndgetAllTasks(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Task[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("getAllTasksForProjectReturn")]
    public Task[] getAllTasksForProject(int projectId) {
        object[] results = this.Invoke("getAllTasksForProject", new object[] {
                    projectId});
        return ((Task[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllTasksForProject(int projectId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllTasksForProject", new object[] {
                    projectId}, callback, asyncState);
    }
    
    /// <remarks/>
    public Task[] EndgetAllTasksForProject(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Task[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("addTaskStatusReturn")]
    public int addTaskStatus(TaskStatus status, int projectId) {
        object[] results = this.Invoke("addTaskStatus", new object[] {
                    status,
                    projectId});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddTaskStatus(TaskStatus status, int projectId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addTaskStatus", new object[] {
                    status,
                    projectId}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndaddTaskStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute(MessageName="addTaskStatus1")]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("addTaskStatusReturn")]
    public int addTaskStatus(TaskStatus status) {
        object[] results = this.Invoke("addTaskStatus1", new object[] {
                    status});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddTaskStatus1(TaskStatus status, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addTaskStatus1", new object[] {
                    status}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndaddTaskStatus1(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    public void dropTaskStatus(int statusId) {
        this.Invoke("dropTaskStatus", new object[] {
                    statusId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindropTaskStatus(int statusId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("dropTaskStatus", new object[] {
                    statusId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnddropTaskStatus(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    public void modifyTaskStatus(TaskStatus status) {
        this.Invoke("modifyTaskStatus", new object[] {
                    status});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginmodifyTaskStatus(TaskStatus status, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("modifyTaskStatus", new object[] {
                    status}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndmodifyTaskStatus(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("getTaskStatusReturn")]
    public TaskStatus getTaskStatus(int statusId) {
        object[] results = this.Invoke("getTaskStatus", new object[] {
                    statusId});
        return ((TaskStatus)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTaskStatus(int statusId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTaskStatus", new object[] {
                    statusId}, callback, asyncState);
    }
    
    /// <remarks/>
    public TaskStatus EndgetTaskStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TaskStatus)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("getAllTaskStatusForProjectReturn")]
    public TaskStatus[] getAllTaskStatusForProject(int projectId) {
        object[] results = this.Invoke("getAllTaskStatusForProject", new object[] {
                    projectId});
        return ((TaskStatus[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllTaskStatusForProject(int projectId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllTaskStatusForProject", new object[] {
                    projectId}, callback, asyncState);
    }
    
    /// <remarks/>
    public TaskStatus[] EndgetAllTaskStatusForProject(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TaskStatus[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("addCommentForTaskReturn")]
    public int addCommentForTask(Task task, Comment comment) {
        object[] results = this.Invoke("addCommentForTask", new object[] {
                    task,
                    comment});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddCommentForTask(Task task, Comment comment, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addCommentForTask", new object[] {
                    task,
                    comment}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndaddCommentForTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("getCommentsForTaskReturn")]
    public Comment[] getCommentsForTask(Task task) {
        object[] results = this.Invoke("getCommentsForTask", new object[] {
                    task});
        return ((Comment[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCommentsForTask(Task task, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCommentsForTask", new object[] {
                    task}, callback, asyncState);
    }
    
    /// <remarks/>
    public Comment[] EndgetCommentsForTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Comment[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("addCustomFieldForTaskReturn")]
    public int addCustomFieldForTask(Task task, CustomField customField) {
        object[] results = this.Invoke("addCustomFieldForTask", new object[] {
                    task,
                    customField});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddCustomFieldForTask(Task task, CustomField customField, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addCustomFieldForTask", new object[] {
                    task,
                    customField}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndaddCustomFieldForTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://taskManager.services.projectServer.roundtable.dommoni.com", ResponseNamespace="http://localhost:8080/ProjectServer/services/TaskManager")]
    [return: System.Xml.Serialization.SoapElementAttribute("getAllCustomFieldsForTaskReturn")]
    public CustomField[] getAllCustomFieldsForTask(Task task) {
        object[] results = this.Invoke("getAllCustomFieldsForTask", new object[] {
                    task});
        return ((CustomField[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllCustomFieldsForTask(Task task, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllCustomFieldsForTask", new object[] {
                    task}, callback, asyncState);
    }
    
    /// <remarks/>
    public CustomField[] EndgetAllCustomFieldsForTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CustomField[])(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Task", "http://www.dommoni.com/ROUNDTABLE")]
public class Task : NotificationContextObject {
    
    /// <remarks/>
    public int assignedTo;
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public TaskStatus currentStatus;
    
    /// <remarks/>
    public CustomField[] customFields;
    
    /// <remarks/>
    public string description;
    
    /// <remarks/>
    public System.DateTime dueDate;
    
    /// <remarks/>
    public int flag;
    
    /// <remarks/>
    public bool isPublic;
    
    /// <remarks/>
    public System.DateTime lastModified;
    
    /// <remarks/>
    public NamedFieldCollection[] namedFieldCollections;
    
    /// <remarks/>
    public int percentComplete;
    
    /// <remarks/>
    public int projectId;
    
    /// <remarks/>
    public System.DateTime startDate;
    
    /// <remarks/>
    public TaskReminder taskReminder;
    
    /// <remarks/>
    public string title;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("TaskStatus", "http://www.dommoni.com/ROUNDTABLE")]
public class TaskStatus {
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public int projectId;
    
    /// <remarks/>
    public string title;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("DiscussionMessage", "http://www.dommoni.com/ROUNDTABLE")]
public class DiscussionMessage {
    
    /// <remarks/>
    public int accountId;
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public string messageText;
    
    /// <remarks/>
    public System.DateTime timestamp;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Account", "http://www.dommoni.com/ROUNDTABLE")]
public class Account {
    
    /// <remarks/>
    public int accountType;
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public string nickName;
    
    /// <remarks/>
    public string password;
    
    /// <remarks/>
    public string profile;
    
    /// <remarks/>
    public string username;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("ScheduleItem", "http://www.dommoni.com/ROUNDTABLE")]
public class ScheduleItem {
    
    /// <remarks/>
    public Comment[] comments;
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public string description;
    
    /// <remarks/>
    public System.Single duration;
    
    /// <remarks/>
    public System.DateTime endDate;
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public int ordinal;
    
    /// <remarks/>
    public int percentComplete;
    
    /// <remarks/>
    public int priority;
    
    /// <remarks/>
    public Account[] resources;
    
    /// <remarks/>
    public System.DateTime startDate;
    
    /// <remarks/>
    public string title;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Comment", "http://www.dommoni.com/ROUNDTABLE")]
public class Comment {
    
    /// <remarks/>
    public string comment;
    
    /// <remarks/>
    public string context;
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public int objectId;
    
    /// <remarks/>
    public int projectId;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("TaskReminder", "http://www.dommoni.com/ROUNDTABLE")]
public class TaskReminder {
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public int[] recipients;
    
    /// <remarks/>
    public System.DateTime reminderTime;
    
    /// <remarks/>
    public int taskId;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("NamedFieldCollection", "http://www.dommoni.com/ROUNDTABLE")]
public class NamedFieldCollection {
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public string description;
    
    /// <remarks/>
    public CustomField[] fields;
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public int projectId;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("CustomField", "http://www.dommoni.com/ROUNDTABLE")]
public class CustomField {
    
    /// <remarks/>
    public CustomFieldAttribute[] attributes;
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public bool hidden;
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public int ordinal;
    
    /// <remarks/>
    public int type;
    
    /// <remarks/>
    public CustomFieldValueWrapper valueWrapper;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("CustomFieldAttribute", "http://www.dommoni.com/ROUNDTABLE")]
public class CustomFieldAttribute {
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public string value;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("CustomFieldValueWrapper", "http://www.dommoni.com/ROUNDTABLE")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CustomFieldValueWrapperString))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(CustomFieldValueWrapperInt))]
public abstract class CustomFieldValueWrapper {
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("CustomFieldValueWrapperString", "http://www.dommoni.com/ROUNDTABLE")]
public class CustomFieldValueWrapperString : CustomFieldValueWrapper {
    
    /// <remarks/>
    public string value;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("CustomFieldValueWrapperInt", "http://www.dommoni.com/ROUNDTABLE")]
public class CustomFieldValueWrapperInt : CustomFieldValueWrapper {
    
    /// <remarks/>
    public int value;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("BinaryAttachment", "http://www.dommoni.com/ROUNDTABLE")]
public class BinaryAttachment {
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
    public System.Byte[] attachment;
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public string notes;
    
    /// <remarks/>
    public string objectContext;
    
    /// <remarks/>
    public int objectId;
    
    /// <remarks/>
    public int projectId;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("MeetingNoteItem", "http://www.dommoni.com/ROUNDTABLE")]
public class MeetingNoteItem {
    
    /// <remarks/>
    public BinaryAttachment[] attachments;
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public string description;
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public int meetingId;
    
    /// <remarks/>
    public string title;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("MeetingFollowupItem", "http://www.dommoni.com/ROUNDTABLE")]
public class MeetingFollowupItem {
    
    /// <remarks/>
    public int ordinal;
    
    /// <remarks/>
    public string text;
    
    /// <remarks/>
    public string title;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("MeetingAgendaItem", "http://www.dommoni.com/ROUNDTABLE")]
public class MeetingAgendaItem {
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public string notes;
    
    /// <remarks/>
    public int ordinal;
    
    /// <remarks/>
    public string title;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("NotificationContextObject", "http://roundtable.dommoni.com")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Document))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Discussion))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Schedule))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Forum))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Task))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Meeting))]
public abstract class NotificationContextObject {
    
    /// <remarks/>
    public int id;
    
    /// <remarks/>
    public string name;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Document", "http://www.dommoni.com/ROUNDTABLE")]
public class Document : NotificationContextObject {
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public string description;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
    public System.Byte[] document;
    
    /// <remarks/>
    public int documentType;
    
    /// <remarks/>
    public string filename;
    
    /// <remarks/>
    public int ownerId;
    
    /// <remarks/>
    public int projectId;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Discussion", "http://www.dommoni.com/ROUNDTABLE")]
public class Discussion : NotificationContextObject {
    
    /// <remarks/>
    public System.DateTime date;
    
    /// <remarks/>
    public int[] memberIds;
    
    /// <remarks/>
    public DiscussionMessage[] messages;
    
    /// <remarks/>
    public int projectId;
    
    /// <remarks/>
    public string title;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Schedule", "http://www.dommoni.com/ROUNDTABLE")]
public class Schedule : NotificationContextObject {
    
    /// <remarks/>
    public int accessMode;
    
    /// <remarks/>
    public Comment[] comments;
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public int projectId;
    
    /// <remarks/>
    public System.DateTime scheduleEndDate;
    
    /// <remarks/>
    public ScheduleItem[] scheduleItems;
    
    /// <remarks/>
    public System.DateTime scheduleStartDate;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Forum", "http://www.dommoni.com/ROUNDTABLE")]
public class Forum : NotificationContextObject {
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public string message;
    
    /// <remarks/>
    public int projectId;
    
    /// <remarks/>
    public string subject;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Meeting", "http://www.dommoni.com/ROUNDTABLE")]
public class Meeting : NotificationContextObject {
    
    /// <remarks/>
    public MeetingAgendaItem[] agendaItems;
    
    /// <remarks/>
    public int[] attendees;
    
    /// <remarks/>
    public int createdBy;
    
    /// <remarks/>
    public System.DateTime createdOn;
    
    /// <remarks/>
    public string description;
    
    /// <remarks/>
    public System.DateTime endTime;
    
    /// <remarks/>
    public MeetingFollowupItem[] followupItems;
    
    /// <remarks/>
    public MeetingNoteItem[] meetingNotes;
    
    /// <remarks/>
    public int projectId;
    
    /// <remarks/>
    public bool sendInvitation;
    
    /// <remarks/>
    public System.DateTime startTime;
    
    /// <remarks/>
    public string title;
}
